# Module: elasticsearch
# Docs: https://www.elastic.co/guide/en/beats/metricbeat/6.7/metricbeat-module-elasticsearch.html

- module: elasticsearch
  metricsets:
    - ccr
    - cluster_stats
    - index
    - index_recovery
    - index_summary
    - ml_job
    - node_stats
    - shard
  period: 10s
  hosts: ["localhost:9200"] 
  xpack.enabled: true
